### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by AccidentGrotesque** [Mark2Mark/Show-Node-Count#3]
The Plugin ShowNodeCount.glyphsReporter has caused a crash. Please update it by opening the Plugin Manager or re-downloading it from the original source.

Details:
Traceback (most recent call last):

  File "~/Library/Application Support/Glyphs/Plugins/ShowNodeCount.glyphsReporter/Contents/Resources/plugin.py", line 25, in <module>
    class ShowNodeCount(ReporterPlugin):

BadPrototypeError: Objective-C expects 6 arguments, Python argument has 5 arguments for <unbound selector drawTextAtPoint of ShowNodeCount at 0x11e418db0>

App:2.6.6-1352 Plugin:1.2-120

**Comment by Mark2Mark** [comment]
Oops, I can’t reproduce neither in G2 nor in G3

Could you try to open the Plugin Manager and maybe uninstall and re-install?

**Comment by AccidentGrotesque** [comment]
Hi Mark

Danke für die rasche Antwort! In G2 ist der "Node Counter" eben nicht im Plug-in Manager aufgeführt, sonst hätte ichs schon lange so gemacht. Auch hab ich noch Version 1.1.4 installiert, weil die Version 1.2 nicht läuft.

In G3 aber soweit auch alles bestens.

Liebe Grüsse,
Reto

> Am 06.09.2021 um 18:31 schrieb Mark Frömberg ***@***.***>:
> 
> 
> Oops, I can’t reproduce neither in G2 nor in G3
> 
> Could you try to open the Plugin Manager and maybe uninstall and re-install?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> 







------------------------------------------

Grilli Type AG
Reto Moser

E   ***@***.***
www.grillitype.com

**Comment by Mark2Mark** [comment]
Thanks, danke!

Das wusste ich gar nicht. Irgendwer muss den da rausgenommen haben. @mekkablue / @schriftgestalt ?

Habe mal versucht ihn wieder reinzupacken.
https://github.com/schriftgestalt/glyphs-packages/commit/dd485774cb4da05f56b2c840e9bd54f8ed0e7ecc

**Comment by AccidentGrotesque** [comment]
kk, danke! Dann hoffe ich mal, Rainer ist hier so schnell wie im GL Forum ;)

Lg R

> Am 06.09.2021 um 19:42 schrieb Mark Frömberg ***@***.***>:
> 
> 
> Thanks, danke!
> 
> Das wusste ich gar nicht. Irgendwer muss den da rausgenommen haben. @mekkablue / @schriftgestalt ?
> 
> Habe mal versucht ihn wieder reinzupacken.
> ***@***.***
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> 





------------------------------------------

Grilli Type AG
Reto Moser

E   ***@***.***
www.grillitype.com

**Comment by Mark2Mark** [comment]
Sollte aber auch ohne Rainer schon im Plugin Manager sein, bei mir wird es schon wieder angezeigt :)


LGM

**Comment by AccidentGrotesque** [comment]
Moin!

Plugin nun wieder im Manager, TOP! Aber, 1.2 installiert und grad schon wieder diese Fehlermeldung beim booten von GL:

----------------------

The Plugin ShowNodeCount.glyphsReporter has caused a crash. Please update it by opening the Plugin Manager or re-downloading it from the original source.

Details:
Traceback (most recent call last):

  File "~/Library/Application Support/Glyphs/Repositories/Show Node Count/ShowNodeCount.glyphsReporter/Contents/Resources/plugin.py", line 25, in <module>
    class ShowNodeCount(ReporterPlugin):

BadPrototypeError: Objective-C expects 6 arguments, Python argument has 5 arguments for <unbound selector drawTextAtPoint of ShowNodeCount at 0x11b0a5db0>

App:2.6.6-1352 Plugin:1.2-120

------------------------

Kannst du damit etwas anfangen?

Lg Reto


> Am 06.09.2021 um 21:43 schrieb Mark Frömberg ***@***.***>:
> 
> 
> Sollte aber auch ohne Rainer schon im Plugin Manager sein, bei mir wird es schon wieder angezeigt :)
> 
> LGM
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> 





------------------------------------------

Grilli Type AG
Reto Moser

E   ***@***.***
www.grillitype.com

**Comment by Mark2Mark** [comment]
Moin, kannst du mal bitte auf das Plugin `ShowNodeCount.glyphsReporter` rechts-klicken > "Show Package Contents", und dann darin die `Info.plist` aufmachen? welche Version steht dort bei `CFBundleVersion`?

Soll:
```plist
	<key>CFBundleShortVersionString</key>
	<string>1.3</string> <!-- 1.0 -->
	<key>CFBundleVersion</key>
	<string>122</string> <!-- 123 -->
```

**Comment by AccidentGrotesque** [comment]
Klar, bei mir siehts so aus:

	<key>CFBundleShortVersionString</key>
	<string>1.2</string> 
	<key>CFBundleVersion</key>
	<string>120</string>

**Comment by Mark2Mark** [comment]
das erste muss `1.3` sein, das letzte `122`. Dann ist das Update irgendwie nicht angekommen, glaube.

einfach mal löschen (am besten aus dem "Repositories" Ordner und neu aus dem PM installieren.

**Comment by schriftgestalt** [comment]
Es geht im Glyphs 2. Has repariert. Bitte das plugin noch einmal neu laden.

**Comment by AccidentGrotesque** [comment]
Jetzt hats geklappt! Super danke dir 1000 für den Support. Das plugin ist ja zwar nur was ganz kleines, aber unglaublich hilfreich 🔝

**Comment by Mark2Mark** [comment]
Sehr gerne, danke auch an Georg! Freut mich wenn es hilft.
